"""Build archive.zip for H3 + range-coded mask test.

Layout (single 'p' blob inside archive.zip):
  [u32 mask_size][mask_bytes]
  [u32 pose_size][pose_bytes]
  [u32 model_size][model_bytes]

mask_bytes  = range_mask_codec adaptive9bin output on (600, 512, 384) transpose
pose_bytes  = brotli of float32 (600, 6) numpy array
model_bytes = brotli of torch.save() of state_dict (simplest path; ~327 KB)
"""
import io, os, struct, subprocess, sys, tempfile, zipfile
from pathlib import Path
import brotli, numpy as np, torch

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(ROOT / "autoresearch"))
sys.path.insert(0, str(ROOT))

# H3 model checkpoint — local copy bundled with this submission for reproducibility.
# Falls back to the autoresearch path if the local copy is missing.
_LOCAL_CKPT = HERE / "encode_artifacts" / "h3_BEST.ckpt"
CKPT_PATH = _LOCAL_CKPT if _LOCAL_CKPT.exists() else (ROOT / "autoresearch" / "colab_run" / "h3_continue" / "h3_BEST.ckpt")
# Data cache (600 SegNet masks + PoseNet poses extracted from the public test videos).
# Generated by autoresearch/scripts; see README. Not bundled (3.6 GB).
DATA_CACHE = ROOT / "autoresearch" / "_cache" / "full_split_600all.pt"
CODEC_SRC = HERE / "range_mask_codec.cpp"
CODEC_BIN = HERE / "range_mask_codec.exe"
ARCHIVE_OUT = HERE / "archive.zip"

def compile_codec():
    if CODEC_BIN.exists() and CODEC_BIN.stat().st_mtime > CODEC_SRC.stat().st_mtime:
        return
    print(f"[build] compiling {CODEC_SRC.name}")
    subprocess.run(["g++", "-O3", "-std=c++17", str(CODEC_SRC), "-o", str(CODEC_BIN)], check=True)

# Adaptive band-tile structure: 4 horizontal bands of equal H=128, with W splits
# tuned per band (sky/road bands compress fine with 3 W-splits, busy horizon
# bands need 8). Total 22 chunks. Found via sweep over many tilings.
MASK_BAND_W_SPLITS = (3, 8, 8, 3)
MASK_H_PART = 128  # 4 equal bands of 128 rows in transposed (600, 512, 384) layout
MASK_TILE_TRANSFORMS = (
    "id", "revHW", "revT_revH",
    "id", "id", "id", "revT", "revT", "revH", "revT", "id",
    "id", "id", "id", "revW", "revT_revH", "revT_revHW", "id", "id",
    "id", "id", "id",
)

def apply_mask_tile_transform(chunk, tag):
    """Static per-tile lossless scan transform found by _mask_encoder_arch_research."""
    ops = set(tag.split("_"))
    out = chunk
    if "revT" in ops:
        out = out[::-1, :, :]
    if "revH" in ops or "revHW" in ops:
        out = out[:, ::-1, :]
    if "revW" in ops or "revHW" in ops:
        out = out[:, :, ::-1]
    return np.ascontiguousarray(out)

def encode_mask(masks_uint8):
    """Encode (600, 384, 512) masks via range_mask_codec adaptive9bin.

    Layout: transpose to (600, 512, 384), 4 H-bands of 128 rows, each band
    independently W-split per MASK_BAND_W_SPLITS. Each tile is its own
    range-coded bitstream.

    Wire format:
      [u32 n_chunks][u32 size_0][bytes_0][u32 size_1][bytes_1]...
    Decoder iterates row-major (band i, w-split j).
    """
    m_t = np.ascontiguousarray(masks_uint8.transpose(0, 2, 1))  # (600, 512, 384)
    streams = []
    tile_idx = 0
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        for i, n_w in enumerate(MASK_BAND_W_SPLITS):
            w_part = 384 // n_w
            for j in range(n_w):
                chunk = np.ascontiguousarray(
                    m_t[:, i*MASK_H_PART:(i+1)*MASK_H_PART, j*w_part:(j+1)*w_part])
                chunk = apply_mask_tile_transform(chunk, MASK_TILE_TRANSFORMS[tile_idx])
                raw = td / f"c_{i}_{j}.raw"
                out = td / f"c_{i}_{j}.bin"
                raw.write_bytes(chunk.tobytes())
                subprocess.run([str(CODEC_BIN), str(raw), "600", str(MASK_H_PART),
                                str(w_part), str(out), "adaptive9bin"], check=True)
                streams.append(out.read_bytes())
                tile_idx += 1
    if tile_idx != len(MASK_TILE_TRANSFORMS):
        raise RuntimeError(f"mask tile transform count mismatch: {tile_idx} vs {len(MASK_TILE_TRANSFORMS)}")
    parts = [struct.pack("<I", len(streams))]
    for s in streams:
        parts.append(struct.pack("<I", len(s)))
        parts.append(s)
    return b"".join(parts)

POSE_BITS_PER_DIM = (14, 4, 4, 4, 4, 4)  # extreme aggression on small dims

def encode_pose(poses):
    """poses: (600, 6) float32. Per-dim N-bit quantization with fp32 lo/scale headers,
    bit-packed, brotli. Per-dim bit allocation tuned via sweep — dim 0 gets 14 bits
    (its range is 12.0 vs 0.06-0.2 for other dims)."""
    n_pair, n_dim = poses.shape
    bits_per_dim = POSE_BITS_PER_DIM
    if len(bits_per_dim) != n_dim:
        raise ValueError(f"bit allocation has {len(bits_per_dim)} dims, expected {n_dim}")
    parts = [struct.pack("<II", n_pair, n_dim)]
    parts.append(bytes(bits_per_dim))  # one byte per dim
    bit_buf = []
    for d in range(n_dim):
        col = poses[:, d].astype(np.float32)
        bits = bits_per_dim[d]
        lo, hi = float(col.min()), float(col.max())
        scale = (hi - lo) / ((1 << bits) - 1)
        if scale == 0: scale = 1e-9
        q = np.round((col - lo) / scale).astype(np.uint32)
        parts.append(struct.pack("<ff", lo, scale))
        for v in q:
            for b in range(bits):
                bit_buf.append((int(v) >> (bits - 1 - b)) & 1)
    while len(bit_buf) % 8: bit_buf.append(0)
    bs = bytearray()
    for i in range(0, len(bit_buf), 8):
        byte = 0
        for b in range(8):
            byte = (byte << 1) | bit_buf[i + b]
        bs.append(byte)
    parts.append(bytes(bs))
    return brotli.compress(b"".join(parts), quality=11)

def encode_model_naive(sd):
    """Simplest packing: torch.save() the whole state_dict, brotli it."""
    buf = io.BytesIO()
    torch.save(sd, buf)
    return brotli.compress(buf.getvalue(), quality=11)


def encode_model_flat_fp4(gen, sd):
    """Flat-FP4 packing. Pack weights per the static schema, brotli the result.
    Returns (model_bytes_brotli, schema). Schema must match decoder's hard-coded SCHEMA."""
    sys.path.insert(0, str(HERE))
    from flat_fp4 import build_schema, encode
    from model import apply_fp4_to_model
    apply_fp4_to_model(gen)  # quantize in-place so we encode the actual FP4 levels
    sd_q = dict(gen.state_dict())
    schema = build_schema(gen)
    raw = encode(sd_q, schema)
    return brotli.compress(raw, quality=11), schema

def build_payload(mask_bytes, pose_bytes, model_bytes, sidecar_bytes=b""):
    """Concat with u32 length prefixes."""
    parts = [
        struct.pack("<I", len(mask_bytes)), mask_bytes,
        struct.pack("<I", len(pose_bytes)), pose_bytes,
        struct.pack("<I", len(model_bytes)), model_bytes,
    ]
    if sidecar_bytes:
        parts.append(struct.pack("<I", len(sidecar_bytes)))
        parts.append(sidecar_bytes)
    return b"".join(parts)

def main():
    compile_codec()

    # Load source data
    print(f"[build] loading data from {DATA_CACHE}")
    d = torch.load(DATA_CACHE, map_location="cpu", weights_only=True)
    masks = d["train_masks"].numpy()        # (600, 384, 512) uint8
    poses = d["train_poses"].numpy()        # (600, 6) float32
    print(f"  masks {masks.shape} {masks.dtype}, poses {poses.shape}")

    # Load model + build it
    print(f"[build] loading H3 ckpt from {CKPT_PATH}")
    sd = torch.load(CKPT_PATH, map_location="cpu", weights_only=True)
    print(f"  {len(sd)} tensors, {sum(v.numel() for v in sd.values())} params")

    # Encode each piece
    print("[build] encoding mask via range codec...")
    mask_bytes = encode_mask(masks)
    print(f"  mask: {len(mask_bytes)} bytes")

    print("[build] encoding pose...")
    pose_bytes = encode_pose(poses)
    print(f"  pose: {len(pose_bytes)} bytes")

    print("[build] packing model (flat-FP4 + brotli)...")
    sys.path.insert(0, str(HERE))
    from model import GeneratorPoseLR
    gen = GeneratorPoseLR()
    gen.load_state_dict(sd, strict=True)
    model_bytes, schema = encode_model_flat_fp4(gen, sd)
    print(f"  model: {len(model_bytes)} bytes (schema entries: {len(schema)})")

    # Optional sidecar blob (path provided via SIDECAR_PATH env)
    sidecar_bytes = b""
    sidecar_path = os.environ.get("SIDECAR_PATH", "")
    if sidecar_path and Path(sidecar_path).exists():
        sidecar_bytes = Path(sidecar_path).read_bytes()
        print(f"[build] sidecar: {len(sidecar_bytes)} bytes from {sidecar_path}")

    # Combine into single payload
    payload = build_payload(mask_bytes, pose_bytes, model_bytes, sidecar_bytes)
    print(f"[build] total payload: {len(payload)} bytes")

    # Write to archive.zip with single entry "p"
    with zipfile.ZipFile(ARCHIVE_OUT, "w", zipfile.ZIP_STORED) as zf:
        zf.writestr("p", payload)
    sz = ARCHIVE_OUT.stat().st_size
    print(f"[build] wrote {ARCHIVE_OUT} = {sz} bytes")
    print(f"[build] rate = 25 * {sz} / 37545489 = {25 * sz / 37545489:.4f}")

if __name__ == "__main__":
    main()
